export const Users = [{
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Zainab Elsayed",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Youssef Ahmed",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Menna karam",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Yasmeen Alaa",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Nesma farag",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "Rodina Mohamed",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Asmaa Adel",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "Kristen hana",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpeg",
        username: "sabry wagdi",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpeg",
        username: "faten Eldesoky",
    },
    {
        id: 11,
        profilePicture: "assets/person/download.png",
        username: "ITI",
    },
    {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Zainab Elsayed",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Youssef Ahmed",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Menna karam",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Yasmeen Alaa",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Nesma farag",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "Rodina Mohamed",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Asmaa Adel",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "Kristen hana",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpeg",
        username: "sabry wagdi",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpeg",
        username: "faten Eldesoky",
    },
    {
        id: 11,
        profilePicture: "assets/person/download.png",
        username: "ITI",
    },
];

export const Posts = [{
        id: 1,
        desc: "The Minister of Communications and Information Technology Amr Talaat has witnessed the commencement ceremony of the Information Technology Institute (ITI)2019-2020 training year",
        photo: "assets/post/p1.png",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "ITI premises in Smart Village.   The commencement included an open meeting with some of the graduates of the various ",
        photo: "assets/post/p2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "programs and specializations, from different governorates. During the meeting, ITI various training programs were presented",
        photo: "assets/post/p3.jpg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        desc: "training program for recruits, with around 5,500 graduates in the previous training year.",
        photo: "assets/post/p4.jpg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        desc: "he meeting, in addition, shed light on the job opportunities that the IT industry helped create in local and international markets through",
        photo: "assets/post/p6.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        photo: "assets/post/p7.jpg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "technological innovation hub in Aswan will be inaugurated, including branches of MCIT affiliated training institutes. .",
        photo: "assets/post/p5.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        desc: "governorates and from outside Egypt, and supporting the services of introducing technological professions and their future through Mahara-Tech..",
        photo: "assets/post/p2.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "governorates and from outside Egypt, and supporting ",
        photo: "assets/post/p7.jpg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        desc: " technological professions and their future through Mahara-Tech.",
        photo: "assets/post/p3.jpg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];
export const Newz = [{
        id: 1,
        desc: "The Minister of Communications and Information Technology Amr Talaat has witnessed t",
        photo: "assets/news/new (1).jpg",
        date: "22/11/2021",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "ITI premises in Smart Village.   The commencement included an open meeting  ",
        photo: "assets/news/new (2).jpg",
        date: "25/12/2021",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "programs and specializations, from different governorates. During the meeting ",
        photo: "assets/news/new (3).jpg",
        date: "27/11/2021",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        desc: "training program for recruits, with around 5,500 graduates in the previous ",
        photo: "assets/news/new (4).jpg",
        date: "27/11/2021",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        desc: "he meeting, in addition, shed light on the job opportunities that the IT  ",
        photo: "assets/news/new (5).jpg",
        date: "27/11/2021",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide ",
        photo: "assets/news/new (6).jpg",
        date: "27/11/2021",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "technological innovation hub in Aswan will be inaugurated, including branches .",
        photo: "assets/news/new (6).jpg",
        date: "27/11/2021",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        desc: "governorates and from outside Egypt, and supporting the services of introducing  ",
        photo: "assets/news/new (1).jpg",
        date: "27/11/2021",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "governorates and from outside Egypt, and supporting ",
        photo: "assets/news/new (2).jpg",
        date: "27/11/2021",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        desc: " technological professions and their future through Mahara-Tech.",
        photo: "assets/news/new (3).jpg",
        date: "27/11/2021",
        userId: 10,
        like: 104,
        comment: 12,
    },
];
export const jobs = [{
        id: 0,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 1,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 2,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 3,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 4,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 5,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
];
//
export const Tracks = [{
        id: 1,
        trackName: "UX UI",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 9,
        photo: "assets/news/COVER (4).jpg",
    },
    {
        id: 2,
        trackName: "AWS",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 9,
        photo: "assets/news/COVER (3).jpg",
    },
    {
        id: 3,
        trackName: "ERP",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 3,
        photo: "assets/news/COVER (2).jpg",
    },
    {
        id: 4,
        trackName: "Front End ",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 3,
        photo: "assets/news/COVER (1).jpeg",
    },
    {
        id: 5,
        trackName: "Back end with php",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 9,
        photo: "assets/news/COVER (1).jpg",
    },
    {
        id: 6,
        trackName: "Front End",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 3,
        photo: "assets/news/COVER (1).jpeg",
    },
];