export const Newz = [{
        desc: "ReactJS is an open-source JavaScript library and has been popular in the town since its inception. ReactJS ...",
        photo: "assets/news/tech (2).png",
        name: "ReactJS",
    },
    {
        desc: "PWAs are progressive web applications – a term coined by a Google engineer. The idea behind PWAs is to pro ...  ",
        photo: "assets/news/tech5.jpg",
        name: "PWAs",
    },
    {
        desc: "Animation is a great way to capture a user’s attention on a fairly simple subject. For example....",
        photo: "assets/news/tech (1).gif",
        name: "Animation",
    },
    {
        desc: "The final front end development trend in our list is GraphQL. GraphQL is a Facebook project developed to fetch d ...",
        photo: "assets/news/tech (1).png",
        name: "GraphQL",
    },

    {
        desc: "Angular is a TypeScript web application framework, and a reliable component of the MEAN tech stack — or MongoDB, ...  ",
        photo: "assets/news/tech (1).jpg",
        name: "Angular",
    },
    {
        desc: "Vue.js is a progressive, MVVM JavaScript framework. By being progressive, Vue.js encourages incremental... ",
        photo: "assets/news/tech7.jpg",
        name: "Vue.js",
    },
];
export const jobs = [{
        id: 0,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 1,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 2,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 3,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 4,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
    {
        id: 5,
        jobName: "Front End Developer (React JS)",
        company: "eMushrif-",
        adress: " Cairo, Egypt",
        jobTitle: "Entry Level · 1-4 Yrs of Exp · Agile · Computer Science · Docker · Information Technology (IT) · Js · Node.js · Redux · Scrum · Software Development · Web Development ",
    },
];
//
export const Tracks = [{
        id: 1,
        trackName: "UX UI",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 9,
        photo: "assets/news/COVER (4).jpg",
    },
    {
        id: 2,
        trackName: "AWS",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 9,
        photo: "assets/news/COVER (3).jpg",
    },
    {
        id: 3,
        trackName: "ERP",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 3,
        photo: "assets/news/COVER (2).jpg",
    },
    {
        id: 4,
        trackName: "Front End ",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 3,
        photo: "assets/news/COVER (1).jpeg",
    },
    {
        id: 5,
        trackName: "Back end with php",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 9,
        photo: "assets/news/COVER (1).jpg",
    },
    {
        id: 6,
        trackName: "Front End",
        desc: " The ICT Minister underlined that MCIT and its affiliated organizations provide lots of opportunities and training programs to hone the youth’s digital skills",
        job_profiles: "UI Developer,Frontend Developer,JavaScript Developer",
        trackduration: 3,
        photo: "assets/news/COVER (1).jpeg",
    },
];